### ISSUE TITLE
Failed connection when using 127.0.0.1

### ISSUE THREAD

**Issue by cavedweller** [molnarg/node-http2#69] opened 2014-06-18 18:54 UTC
This does work when connecting using localhost instead. 
Wireshark traces:
 http://benbrittain.com/static/functioning.pcapng (using localhost)
 http://benbrittain.com/static/notfunctioning.pcapng (using 127.0.0.1)

**Comment by molnarg** [comment] 2015-03-28 15:50
I think I could reproduce the issue. When opening the page as 127.0.0.1 with Firefox, the Server Name Indication (SNI) TLS extension was not used. Since the standard says this:

    The TLS implementation MUST support the Server Name Indication (SNI)
    [TLS-EXT] extension to TLS.  HTTP/2 clients MUST indicate the target
    domain name when negotiating TLS.

The server switches to fallback mode when SNI is not used, and starts speaking HTTP/1.1. Meanwhile, the client thinks the connection HTTP/2 so they end up speaking different protocols and disconnect as soon as one of them can't parse a message.

On the server side, it's clear that it's not an acceptable behaviour so I've changed to code to not require SNI. @todesschaf do you think this should be fixed in Firefox?

**Comment by molnarg** [comment] 2015-03-28 15:51
I've just checked and can confirm that Chrome uses SNI even when for IP addresses.

**Closed** 2015-03-28 15:55 UTC

**Comment by todesschaf** [comment] 2015-03-30 19:41
Hrm, I'll have to check the SNI spec to see who's Doing It Wrong(tm), Firefox or Chrome (or, for all I know, it could be entirely unspecified). It quite likely could be a bug in Firefox.

FWIW, I'm of the opinion that the fallback to HTTP/1.1 without SNI was the right behavior on node-http2's part, given the spec requires SNI and Firefox wasn't sending it (in this one case). I'll circle back around when I have more info.

**Comment by todesschaf** [comment] 2015-03-31 15:23
So I've had a look at the SNI spec, and it looks like, according to a plain text reading of https://tools.ietf.org/html/rfc6066#section-3, Firefox is correct here (the relevant quote - 'Literal IPv4 and IPv6 addresses are not permitted in "HostName".') However, there is no normative (rfc2119) language around that, so I suppose there's an argument to be made that it's a grey area (even though I think the language is pretty straightforward).

We know chrome sends SNI with an IP address. I'll check around the other major browsers that support spdy and/or h2 (namely recent safari and IE), and I'll see if there's a pattern to sending IPs in SNI that supports filing a bug in either firefox or chrome.

**Comment by todesschaf** [comment] 2015-04-03 17:39
I'm not sure that the h2 spec contradicts the SNI spec so much as it just fails to take the reality of the SNI spec into account, causing it to be impossible to speak h2 to an IP host :) Either way, though, it does seem like a bug/oversight in h2. I'll discuss with mt, but I'm betting that at this point in the process, there's not much to be done about it.

Also, I checked Safari and IE, and Safari behaves the same as Chrome (sends SNI even for an IP, in violation of RFC 6066), but IE behaves the same as Firefox (at least IE 11 on Win 7). I'm trying to get my hands on a version of windows that can run a version of IE that supports SPDY and/or h2, so I can see if it behaves differently when sending ALPN (which IE 11 on win 7 doesn't), but I don't expect it to. (Though perhaps it has the same bug as Firefox, where it will advertise h2 when not sending SNI.)

I've opened https://bugzilla.mozilla.org/show_bug.cgi?id=1150195 to fix Firefox to not advertise h2 when we're not sending SNI, to bring us in compliance with the h2 spec.

I still think this change should be rolled back, as once I fix the above bug, Firefox will be in the same state of not being able to speak h2 to an IP address, but then we'll at least know why and have the spec to back us up on it :)

**Comment by martinthomson** [comment] 2015-04-03 18:09
I think that the only sensible thing to do here is to send SNI for names and not for IP addresses.  I think that we should still advertise "h2" though.  Otherwise, we get into all sorts of mess.

As for the specification, I still have AUTH48 coming.  I can qualify this.  More so if you get something to the list.

**Comment by todesschaf** [comment] 2015-04-03 18:14
OK, so sounds like Firefox's behavior is right, and node-http2's behavior *with*  ffd178c is probably the right thing to be doing, even if it isn't exactly 100% spec-compliant.

**Comment by martinthomson** [comment] 2015-04-03 18:16
That looks good to me.  You could add a knob to control that behaviour, but I think that this is the pragmatic option.
