### ISSUE TITLE
`request()` does not actually have `plain` option

### ISSUE THREAD

**Issue by thammi** [molnarg/node-http2#212] opened 2016-07-24 20:29 UTC
The API page claims that `request()` has the additional `plain` option. This is not true as `request()` is actually `requestTSL()` which overwrites `plain` to `false` (see [here](https://github.com/molnarg/node-http2/blob/master/lib/http.js#L637)). Raw requests are supported through `exports.raw` which does no seem to be documented at all.

**Comment by nwgh** [comment] 2016-08-01 15:42
Indeed, the docs need fixed up & regenerated (which I am, obviously, too lazy to do). Dupe of #139

**Closed by nwgh** 2016-08-01 15:42 UTC
Labels: documentation, duplicate
